openapi: '3.0.0'
info:
  version: '1.0'
  title: 'Dictionary API Specification'
  contact:
    name: 'Julius Canute'
    url: 'https://www.juliuscanute.com'
    email: 'juliuscanute@touchcapture.net'
servers:
  - url: '{protocol}://{server}:7071/api'
    variables:
      server:
        default: localhost
      protocol:
        enum:
          - http
          - https
        default: http

tags:
  - name: 'Query Dictionary'

paths:

  /v1/dictionary/pages:
    get:
      tags:
        - 'Query Dictionary'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page'
              example:
                start: 1
                end: 3
                recordsPerPage: 10

  /v1/dictionary/page/{pageNo}:
    get:
      tags:
        - 'Query Dictionary'
      parameters:
        - name: pageNo
          in: path
          required: true
          description: Page number of the dictionary
          schema:
            type: integer
            format: int64
            minimum: 1
          example: 1
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dictionary'
              example:
                start: 1
                end: 3
                currentPage: 1
                words:
                  - id: 1
                    word: Abarticulation
                    meaning: Articulation, usually that kind of articulation which admits of free motion in the joint; diarthrosis.
                  - id: 2
                    word: Abase
                    meaning: To cast down or reduce low or lower, as in rank, office, condition in life, or estimation of worthiness; to depress; to humble; to degrade.
          '404':
            description: 'Requested page not found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Exception'
                example:
                  date: '2019/01/31 00:00:00'
                  message: 'Page not found'
                  path: '/v1/dictionary/page/4'


  /v1/dictionary:
    get:
      tags:
        - 'Query Dictionary'
      parameters:
        - name: word
          in: query
          required: true
          description: Word to search
          schema:
            type: string
          example: happy
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dictionary'
              example:
                start: 1
                end: 3
                currentPage: 1
                words:
                  - id: 1
                    word: Abarticulation
                    meaning: Articulation, usually that kind of articulation which admits of free motion in the joint; diarthrosis.
                  - id: 2
                    word: Abase
                    meaning: To cast down or reduce low or lower, as in rank, office, condition in life, or estimation of worthiness; to depress; to humble; to degrade.
          '404':
            description: 'Word not found'
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Exception'
                example:
                  date: '2019/01/31 00:00:00'
                  message: 'No matching words found'
                  path: '/v1/dictionary?word="zzzzz"'

components:
  schemas:
    Page:
      type: 'object'
      properties:
        start:
          type: 'integer'
          description: 'Start page number'
        end:
          type: 'integer'
          description: 'End page number'
        recordsPerPage:
          type: 'integer'
          description: 'Records per page'

    Dictionary:
      type: 'object'
      properties:
        start:
          type: 'integer'
          description: 'Start page number'
        end:
          type: 'integer'
          description: 'End page number'
        currentPage:
          type: 'integer'
          description: 'Current page number'
        words:
          type: 'array'
          items:
            $ref: '#/components/schemas/Meaning'

    Meaning:
      type: 'object'
      properties:
        id:
          type: 'integer'
          description: 'Word ID'
        word:
          type: 'string'
          description: 'Word'
        meaning:
          type: 'string'
          description: 'Meaning of the word'

    Exception:
      type: 'object'
      properties:
        date:
          type: 'string'
          format: 'date-time'
          description: 'Date of the request'
        message:
          type: 'string'
          description: 'Description of the error'
        path:
          type: 'string'
          description: 'Identity of the resource'